name: merlin
description: This application is developed in Flutter for reading books in the fb2 format.
publish_to: "none"
version: 1.5.5+21
flutter_svg: ^2.0.7

environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  file_picker: ^8.0.6
  rect_getter: ^1.1.0
  geolocator: ^12.0.0
  url_launcher: ^6.3.1
  path_provider: ^2.1.1
  xml: ^6.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  dynamic_height_grid_view: ^0.0.4
  fluttertoast: ^8.2.2
  http: ^1.1.0
  battery_plus: ^6.0.1
  provider: ^6.0.5
  html: ^0.15.4
  app_links: ^6.1.3
  json_annotation: ^4.9.0
  scrollable_positioned_list: ^0.3.8
  device_info_plus: ^10.1.0
  intl: ^0.19.0
  yandex_mobileads: ^7.1.0
  flutter_screen_wake:
    git:
      url: https://github.com/vladislav-rozhkov/flutter_screen_wake.git
      ref: master
  cached_network_image: ^3.3.0
  archive: ^3.4.9
  uuid: ^4.2.2
  flutter_secure_storage: ^9.0.0
  location: ^7.0.0
  flutter_osm_plugin: ^1.3.7
  showcaseview: ^3.0.0
  appmetrica_plugin: ^2.1.0
  is_first_run: ^1.0.0
  # https://github.com/fluttercommunity/flutter_workmanager/issues/588
  workmanager:
    git:
      url: https://github.com/fluttercommunity/flutter_workmanager.git
      path: workmanager
      ref: main
  flutter_charset_detector: ^5.0.0
  path: ^1.9.1
  path_provider_android: ^2.2.17
  external_path: ^2.2.0
  sembast_sqflite: ^2.2.1
  sembast: ^3.8.5
  sqflite: ^2.4.2
  freezed_annotation: ^3.0.0
  flutter_bloc: ^9.1.1
  equatable: ^2.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0
  freezed: ^3.0.6

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/AppLogo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: ./lib/UI/fonts/MyFlutterApp.ttf
    - family: Tektur
      fonts:
        - asset: ./lib/UI/fonts/Tektur.ttf
  assets:
    #- assets/
    - assets/icon/
    - assets/images/
    - assets/stat.json
