name: merlin
description: This application is developed in Flutter for reading books in the fb2 format.
publish_to: "none"
version: 1.4.7+15
flutter_svg: ^2.0.7

environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.7
  file_picker: ^6.2.0
  geolocator: ^11.0.0
  url_launcher: ^6.1.14
  path_provider: ^2.1.1
  xml: ^6.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  dynamic_height_grid_view: ^0.0.4
  fluttertoast: ^8.2.2
  http: ^1.1.0
  battery: ^2.0.3
  provider: ^6.0.5
  html: ^0.15.4
  uni_links: ^0.5.1
  json_annotation: ^4.8.1
  device_info_plus: ^9.1.0
  intl: ^0.19.0
  yandex_mobileads: ^6.1.0
  flutter_screen_wake: ^1.0.2
  cached_network_image: ^3.3.0
  archive: ^3.4.9
  uuid: ^4.2.2
  flutter_secure_storage: ^9.0.0
  location: ^5.0.3
  flutter_osm_plugin: ^0.70.4
  showcaseview: ^2.1.1
  appmetrica_plugin: ^2.1.0
  is_first_run: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1
  change_app_package_name: ^1.1.0

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/AppLogo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: ./lib/UI/fonts/MyFlutterApp.ttf
    - family: Tektur
      fonts:
        - asset: ./lib/UI/fonts/Tektur.ttf
  assets:
    #- assets/
    - assets/icon/
    - assets/images/
    - assets/stat.json
