name: merlin
description: This application is developed in Flutter for reading books in the fb2 format.
publish_to: "none"
version: 1.3.8+4
flutter_svg: ^2.0.7

environment:
  sdk: ">=3.1.2 <4.0.0"
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.7
  file_picker: ^5.5.0
  open_file: ^3.3.2
  flutter_cache_manager: ^3.3.1
  location: ^5.0.3
  geocoding: ^2.1.1
  geolocator: ^10.0.1
  url_launcher: ^6.1.14
  image_picker: ^1.0.4
  image: ^4.1.3
  path: ^1.8.3
  path_provider: ^2.1.1
  xml: ^6.3.0
  shared_preferences: ^2.2.2
  permission_handler: ^11.0.1
  routemaster: ^1.0.1
  go_router: ^12.0.0
  dynamic_height_grid_view: ^0.0.4
  fluttertoast: ^8.2.2
  http: ^0.13.4
  battery: ^2.0.3
  translator: ^0.1.7
  webview_flutter: ^4.4.1
  country_provider: ^1.0.2
  provider: ^6.0.5
  english_words: ^4.0.0
  html: ^0.15.4
  csc_picker: ^0.2.7
  uni_links: ^0.5.1
  json_annotation: ^4.8.1
  device_info_plus: ^9.1.0
  intl: ^0.18.1
  scrollable_positioned_list: ^0.3.8
  yandex_mobileads: ^6.1.0
  flutter_screen_wake: ^1.0.2
  brightness: ^0.0.1
  cached_network_image: ^3.3.0
  archive: ^3.4.9
  uuid: ^4.2.2
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.7.1
  build_runner: ^2.4.6
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/icon/AppLogo.png"

flutter:
  uses-material-design: true

  fonts:
    - family: MyFlutterApp
      fonts:
        - asset: ./lib/UI/fonts/MyFlutterApp.ttf
    - family: Tektur
      fonts:
        - asset: ./lib/UI/fonts/Tektur.ttf
  assets:
    #- assets/
    - assets/icon/
    - assets/images/
    - assets/stat.json
